type Mutation {
  createPost(
    message: String
    media: String
    duration: Int
    thumbnail: String
  ): String!

  updatePost(
    id: ID!
    message: String
    media: String
    duration: Int
    thumbnail: String
  ): String!

  deletePost(id: ID!): String!
}
