scalar Date

type PostDetail {
  _id: ID!
  post: ID!
  replyCount: Int!
  likeCount: Int!
  viewCount: Int!
  saveCount: Int!
  retweetCount: Int!
  createdAt: Date!
  updatedAt: Date!
  isLiked: Boolean!
  isSaved: Boolean!
}

type Post {
  _id: ID!
  user: User!
  message: String!
  media: String!
  thumbnail: String!
  duration: Int!
  replyPost: Post
  createdAt: Date!
  updatedAt: Date!
  isFollow: Boolean!
}
