services:
  - name: server
    type: web # This is the main web service
    env: docker
    dockerfilePath: Dockerfile
    buildCommand: npm install
    startCommand: npm run dev
    envVars:
      - key: NODE_ENV
        value: production
    plan: starter # Choose the appropriate plan for your needs
    healthCheckPath: /
    healthCheckPort: 8000
    regions: [Singapore]

  - name: worker
    type: worker # This is a worker service that will run the background tasks
    env: docker
    dockerfilePath: Dockerfile
    buildCommand: npm install
    startCommand: node worker.js
    envVars:
      - key: NODE_ENV
        value: production
    plan: starter
    regions: [Singapore]

  - name: redis
    type: redis
    image: redis:latest
    plan: starter
    autoDeploy: true
    regions: [Singapore]
    ports:
      - 6379:6379
