services:
  - name: server
    type: web # This is the main web service
    env: docker
    dockerfilePath: Dockerfile
    buildCommand: npm install
    startCommand: npm run dev
    envVars:
      - key: NODE_ENV
        value: production
    plan: starter # Choose the appropriate plan for your needs
    healthCheckPath: /

  - name: worker
    type: worker # This is a worker service that will run the background tasks
    env: docker
    dockerfilePath: Dockerfile
    buildCommand: npm install
    startCommand: npm run worker
    envVars:
      - key: NODE_ENV
        value: production
    plan: starter

  - name: redis
    type: redis
    plan: starter
