services:
  - name: server
    type: web # This is the main web service
    env: docker
    dockerfilePath: Dockerfile
    buildCommand: npm install
    envVars:
      - key: NODE_ENV
        value: production
    plan: free # Choose the appropriate plan for your needs
    healthCheckPath: /
