enum MESSAGE_TYPE {
  ANYONE
  FOLLOWERS
  FOLLOWINGS
  NO_ONE
}

type Mutation {
  updateUserProfile(
    name: String!
    photo: String!
    bg_photo: String!
    bio: String!
    location: String!
    website: String!
  ): UserProfile!

  updateUserMsgToggle(messageBy: MESSAGE_TYPE!): String!
}
