type UserProfile {
  _id: ID!
  name: String!
  email: String!
  photo: String!
  bg_photo: String
  bio: String!
  location: String!
  website: String!
  messageBy: String!
  createdAt: Date!
  updatedAt: Date!
  followersCount: Int!
  followingCount: Int!
  isFollowed: Boolean!
  userPosts: Int!
  likePosts: Int!
  replyPosts: Int!
  mediaPosts: Int!
  savePosts: Int!
}

type Query {
  getUserProfile(email: String!): UserProfile!

  getUserPosts(userId: ID!, page: Int!): [Post]!

  getUserMediaPosts(userId: ID!, page: Int!): [Post]!

  getUserReplyPosts(userId: ID!, page: Int!): [Reply_Post_Replies]!

  getUserLikePosts(page: Int!): [Post]!

  getUserSavePosts(page: Int!): [Post]!

  getUserSearch(search: String!): [User]!
}
