type Reply_Post_Replies {
  _id: ID!
  user: User!
  message: String!
  media: String!
  thumbnail: String!
  duration: Int!
  replyPost: Post
  createdAt: Date!
  updatedAt: Date!
  replies: [Post]!
}
