type Notofication_Post {
  _id: String!
  user: String!
  message: String
  media: String
}

type Notification {
  _id: String!
  user: String!
  sender: [User!]!
  isRead: Boolean!
  type: String!
  post: Notofication_Post
  replyPost: Notofication_Post
}

type Query {
  getUserNotifications: [Notification]!
}
