type Notification {
  _id: String!
  user: String!
  type: String!
  message: String!
  sender: [User!]!
  totalSenders: Int!
  isRead: Boolean!
  post: Post
  room: Room
}

type Query {
  getUserNotifications(page: Int!): [Notification]!
  getUserNotificationCount: Int!
}
