type URL {
  timestamp: Int!
  signature: String!
  apiKey: String!
  folder: String!
  eager: String!
  url: String!
}

enum FOLDER {
  POST
  CHAT
  THUMBNAIL
  PROFILE
  PROFILE_BG
}

type Query {
  getMediaUrlForImage(folder: FOLDER!): URL!
  getMediaUrlForVideo(folder: FOLDER!): URL!
}
