type Update_Like_Post {
  bool: String!
  count: Int!
}

type Mutation {
  updatePostLike(toggle: Boolean!, id: ID!): Update_Like_Post!
  updatePostSave(toggle: Boolean!, id: ID!): Update_Like_Post!
}
