type Mutation {
  loginUser(email: String!, password: String!): String!
  signUpUserInitial(name: String!, email: String!, password: String!): String!
  resendOtp(email: String!): String!
  signUpUserFinal(otp: String!, email: String!): String!
  forgotPassword(email: String!): String!
  newPassword(resetToken: String!, password: String!): String!
}
