type Chat {
  _id: String!
  room: String!
  sender: String!
  message: String!
  media: String!
  isSeen: Boolean!
  deleted: Boolean!
  createdAt: Date!
  updatedAt: Date!
}

type Query {
  getRoomChats(roomId: ID!, page: Int!): [Chat]!
}
