name: Test

on:
  push:
    branches-ignore:
      - main
  pull_request:
    branches:
      - "**"

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x, 22.x]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Set up environment variables
        run: |
          echo "ENCRYPTION_KEY=${{ secrets.ENCRYPTION_KEY }}" >> $GITHUB_ENV
          echo "ENCRYPTION_IV=${{ secrets.ENCRYPTION_IV }}" >> $GITHUB_ENV
          echo "MY_GMAIL_ID=${{ secrets.MY_GMAIL_ID }}" >> $GITHUB_ENV
          echo "MY_GMAIL_PASSWORD=${{ secrets.MY_GMAIL_PASSWORD }}" >> $GITHUB_ENV
      - name: "Installing Dependencies"
        run: npm i
      - name: "Running test cases"
        run: npm run test
